spring:
  application:
    name: backend
    # datasource:
    #     driver-class-name: org.postgresql.Driver
    #     url: jdbc:postgresql://localhost:5432/backenddb
    #     username: backend
    #     password: backend
    # jpa:
    #     database-platform: org.hibernate.dialect.PostgresSQLDialect
    #     hibernate:
    #         ddl-auto: 'create-drop'

server:
  port: 3000
